coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%   # allow small fluctuations
    patch:
      default:
        target: auto
        threshold: 2%
comment: false
